# Generated by Django 4.2.4 on 2023-08-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_offer_delete_productoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
