# Generated by Django 4.2.4 on 2023-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
