# Generated by Django 4.2.4 on 2023-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_expiry_date_coupon_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(null=True, upload_to='product/images/'),
        ),
    ]
