# Generated by Django 4.2.4 on 2023-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
