# Generated by Django 4.2.4 on 2023-09-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wallet_referral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='userr',
        ),
    ]
