# Generated by Django 4.2.4 on 2023-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_wallet_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refferal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
