# Generated by Django 4.2.4 on 2023-09-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_refferal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refferal_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
