# Generated by Django 4.2.4 on 2023-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_refferal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refferal_code1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
