"""
Django settings for decore project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path,os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@msju-e!q=)1xj2i051(7!d@6iz6hewp4-&i@f)ao@x!v&5ak('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# AUTH_USER_MODEL = 'store.User'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'category',
    'accounts',
    'admindashboard',
    'cart',
    'order',
    'payment',
    'offer',
    'wishlist',
    
    

    # paypal integration

    'paypal.standard.ipn',
   
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'decore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'decore.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'decore1',
        'USER':'postgres',
        'PASSWORD':'12345',
        'HOST':'localhost',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_PASSWORD_RESET_FORM = 'store.forms.CustomPasswordResetForm'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'  # Change this to the correct URL path for serving media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Change this to the correct absolute filesystem path

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# Add this line to specify the URL where users should be redirected after logging out
LOGOUT_REDIRECT_URL = 'home'  # Change 'home' to your desired URL name


# Email 

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER= 'ridhamariyam44@gmail.com'
EMAIL_HOST_PASSWORD= 'fjtrusfpeljaktal'

# payment

# PAYPAL_RECEIVER_EMAIL = 'ridhamariyam44@gmail.com'
# PAYPAL_TEST = True
# PAYPAL_CLIENT_ID = 'AT3kxIhhNFXdohsUr-wFhwMl5_F23bNOLEDnsvLOr2pmzj5q6kvviHVEUuihvzCXv6zEDjt0or-HZRaK'
# PAYPAL_SECRET = 'EF2fZMJgHG-5ttoOqDRJ-ImCgHGV3iRUxleEKtHuzN2R0XfOcR0cLLNQsQsh61rJ-5ZMLjdPpE73dShS'


# payment integration 
KEY = 'rzp_test_syOLTFEUoECCp5'
KEY_SECRET = 'B7ahYnunF7epXGmlbPdpYVdN'

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"